Repository 666ghj/Weibo_PublicOpinion_AnalysisSystem, pull requests merged in 2024-12, with the labels that each got.

#5 强化登录安全以及防止SQL注入问题
  views/user/user.py
Labels: question

#10 优化 topicDefine.py 主题标签处理逻辑，提升性能与稳定性
  model/topicDefine.py
Labels: help wanted

#12 Optimized the web scraping functionality to support multi-account crawling and enhance performance.
  spider/spiderDataPackage/spiderComments.py
  spider/spiderDataPackage/spiderContent.py
  spider/spiderDataPackage/spiderNav.py
Labels: enhancement
